stages:
  - build
  - test
  - report
  - release
  - deploy
  - cleanup

before_script:
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=${PHP_IMAGE_NAME}:${APP_VERSION}
  - export REGISTRY_PHP_IMAGE=${PHP_IMAGE_NAME}:${CI_BUILD_REF_NAME}
  - export ISOLATION=buildpipeline${CI_PIPELINE_ID}
  - export COMPOSE_PROJECT_NAME=${ISOLATION}
  - pwd
  - docker version
  - docker-compose version
  - echo ${ISOLATION}
  - echo ${APP_VERSION}

  # run all commands from test directory
  - cd tests
  - cp .env-dist .env


build:
  stage: build
  script:
    - make build

test:lint:
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
    - make lint
    - cp -r _artifacts /tmp/artifacts-${ISOLATION}
    - make clean

test:codeception:
  stage: test
  script:
    - EXIT_CODE=0
    - cd tests
    - cp .env-dist .env
    - make up setup
    - make run-tests || EXIT_CODE=1
    - cp -r codeception/_output /tmp/artifacts-${ISOLATION}
    - make clean
    - exit ${EXIT_CODE}
  except:
    - coverage

test:coverage:
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
    - EXIT_CODE=0
    - cd tests
    - cp .env-dist .env
    - make PHP_ENABLE_XDEBUG=1 up setup
    - make run-coverage || EXIT_CODE=1
    - cp -r codeception/_output /tmp/artifacts-${ISOLATION}
    - make clean
    - exit ${EXIT_CODE}
  only:
    - coverage

report:
  stage: report
  when: always
  script:
    - cp -r /tmp/artifacts-${ISOLATION} artifacts
  artifacts:
    paths:
      - artifacts

release:
  stage: release
  script:
    - docker login --username ${REGISTRY_USER} --password ${REGISTRY_PASS} ${REGISTRY_HOST}
    - docker tag ${STACK_PHP_IMAGE} ${REGISTRY_PHP_IMAGE}
    - docker push ${REGISTRY_PHP_IMAGE}
  only:
    - latest
    - experimental
    - tags

cleanup:
  stage: cleanup
  when: always
  script:
    - make clean
    - make clean COMPOSE_PROJECT_NAME=${ISOLATION}test:lint
    - cd tests
    - make clean
    - make clean COMPOSE_PROJECT_NAME=${ISOLATION}test:coverage

