stages:
  - build
  - test
  - report
  - release
  - deploy
  - cleanup

before_script:
  # Setup as project variables: PHP_IMAGE_NAME=project/php
  - export APP_VERSION=$(git describe --always --dirty)
  - export STACK_PHP_IMAGE=${PHP_IMAGE_NAME}:${APP_VERSION}
  - export REGISTRY_PHP_IMAGE=${PHP_IMAGE_NAME}:${CI_BUILD_REF_NAME}
  - export ISOLATION=buildref${CI_BUILD_REF}$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export COMPOSE_PROJECT_NAME=${ISOLATION}
  - pwd
  - docker version
  - docker-compose version
  - echo ${ISOLATION}
  - echo ${APP_VERSION}
  - cp .env-dist .env


build:
  stage: build
  script:
    - make build

test:lint:
  stage: test
  script:
    - export COMPOSE_PROJECT_NAME=${ISOLATION}${CI_BUILD_NAME}
    - make lint
    - cp -r _artifacts /tmp/artifacts-${ISOLATION}
    - exit ${ERROR}

test:codeception:
  stage: test
  script:
    - EXIT_CODE=0
    - cd tests && cp .env-dist .env
    - make up setup
    - make run-tests || EXIT_CODE=1
    - cp -r codeception/_output /tmp/artifacts-${ISOLATION}
    - make clean
    - exit ${EXIT_CODE}

report:
  stage: report
  when: always
  script:
    - cp -r /tmp/artifacts-${ISOLATION} artifacts
  artifacts:
    paths:
      - artifacts

release:
  stage: release
  script:
    - docker tag ${STACK_PHP_IMAGE} ${REGISTRY_PHP_IMAGE}
    - docker push ${REGISTRY_PHP_IMAGE}
  only:
    - latest
    - tags

cleanup:
  stage: cleanup
  when: always
  script:
    - make clean
    - cd tests
    - make clean

