version: '2'
services:
    web:
        image: phundament/nginx-one:1.9-5.0.4
        environment:
          - VIRTUAL_HOST=${VIRTUAL_HOST}
          - FASTCGI_PASS_HOST=php
        depends_on:
          - php
        volumes_from:
          - php
        ports:
          - 80
    php:
        image: ${STACK_PHP_IMAGE}
        environment:
          - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
        volumes:
            - /app/web
