# Development stack overrides
#
# Variables are populated with values from `.env`
#
version: '2'
services:
  php:
    build:
      context: .
      # FLAVOUR can be undefinied OR -debian
      # undefined == alpine base image
      # -debian   == debian base image
      dockerfile: Dockerfile${FLAVOUR}
    ports:
      - 80
    depends_on:
      - db
      - redis
    environment:
      - DB_ENV_MYSQL_ROOT_PASSWORD=secret
      # For host-volume development (permissions)
      # For composer usage in container
      - GITHUB_API_TOKEN
      - YII_ENV=dev
      - YII_DEBUG=1
      - APP_MAILER_USE_FILE_TRANSPORT=1
      - APP_ADMIN_PASSWORD=admin1
      - APP_ADMIN_EMAIL=admin@local.develop
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./composer.json:/app/composer.json:delegated
      - ./composer.lock:/app/composer.lock:delegated
      - ./src:/app/src
      - ./vendor:/app/vendor
      - ./_host-volumes/runtime/mysql:/app/runtime/mysql:delegated

  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'
