version: '2'
services:
  web:
    volumes:
      - ./web:/app/web
  php:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
    depends_on:
      - db
    environment:
      # For host-volume development (permissions)
      - MYSQL_ROOT_PASSWORD=secret
      - PHP_USER_ID=1000
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      # For usage with https://github.com/jwilder/nginx-proxy
      # - VIRTUAL_HOST=${VIRTUAL_HOST}
    volumes:
      - ~/.composer/cache:/root/.composer/cache
      - ./composer.json:/app/composer.json
      - ./composer.lock:/app/composer.lock
      - ./src:/app/src
      - ./web:/app/web
      - ./vendor:/app/vendor
      #- ./runtime:/app/runtime
  db:
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    image: percona:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306'